name: GitHub Change Json
description: Github action which lets you to change a value from a json file (e.g. package.json).
author: maxgfr
branding:
  icon: bookmark
  color: red
runs:
  using: node12
  main: dist/index.js

inputs:
  path:
    required: true
    description: Path to package.json
  key:
    required: true
    description: Key that you want to modify in your json
  value:
    required: true
    description: Value linked to the key that you want to modify in your json
  commit:
    required: false
    description: Print arguments used by this action.
